// <auto-generated />
using System;
using ConfigServiceInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfigServiceInfrastructure.Migrations
{
    [DbContext(typeof(SettingDbContext))]
    [Migration("20221220090413_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConfigServiceDomain.Model.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowTextCopy")
                        .HasColumnType("bit");

                    b.Property<Guid>("CardIssuerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EnableLowCardAlert")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableSupplyAlert")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMigrationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<int>("ThemeColor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
